defaults: &defaults
  working_directory: ~/magento
  docker:
  - image: ishakhsuvarov/axp-connector-testing:unit-static-0.1

version: 2

jobs:
  build:
    <<: *defaults
    steps:
    - run: 
        name: Building Magento 2.3-develop
        command: |
          git clone https://github.com/magento/magento2.git --depth 1 --single-branch --branch 2.3-develop .
          mkdir axp-connector

    - checkout:
        path: axp-connector
     
    - restore_cache:
        keys:
          - magento-dependencies-{{ checksum "composer.lock" }}-v1

    - run:
        name: Installing dependencies
        command: composer install -n
        
    - save_cache:
        key: magento-dependencies-{{ checksum "composer.lock" }}-v1
        paths:
          - "vendor"
    
    - run:
        name: Installing axp-connector
        command: |
            composer config minimum-stability dev
            composer config repositories.metapackage path "./*"
            composer config repositories.modules path "./*/*/"
            composer require adobe/axp-connector

    - persist_to_workspace:
        root: .
        paths:
          - .

  unit_test:
    <<: *defaults
    steps:

    - attach_workspace:
        at: .

    - run:
        name: Unit Test
        command: ./vendor/phpunit/phpunit/phpunit -c dev/tests/unit

  static_test:
    <<: *defaults
    steps:

    - attach_workspace:
        at: .

    - run:
        name: Prepare file list
        command: |
          find axp-connector -not -path '*/.*/*' -not -name '.*' -type f -follow -print > dev/tests/static/testsuite/Magento/Test/_files/changed_files_axp.txt
          find axp-connector -not -path '*/.*/*' -not -name '.*' -type f -follow -print > dev/tests/static/testsuite/Magento/Test/_files/changed_files_axp.added.txt

    - run:
        name: Static test
        command: ./vendor/phpunit/phpunit/phpunit -c dev/tests/static

workflows:
  version: 2
  build-test:
    jobs:
    - build
    - unit_test:
        requires:
        - build
    - static_test:
        requires:
        - build
